// constants.js

export const MOCK_SERVICE_REQUESTS = [
    {
        id: '507f1f77bcf86cd799439011',
        fecha: new Date('2024-03-15'),
        mes: 'Marzo',
        especialista: 'Dr. Juan Pérez',
        tipoDeServicio: 'Consulta Psicológica',
        nombrePaciente: 'María Rodriguez',
        edad: 28,
        nacionalidad: 'Dominicana',
        noCedula: '001-0123456-7',
        genero: 'Femenino',
        solicitante: 'Personal',
        nombreSolicitante: 'María Rodriguez',
        direccion: 'Calle Principal #123, Santo Domingo Este',
        tipoDePaciente: 'Ambulatorio',
        afiliacionArs: 'SENASA',
        categoriaDiagnostico: 'Trastornos de ansiedad',
        descripcionDiagnostico: 'Trastorno de ansiedad generalizada',
        medicamento: 'Sertralina 50mg',
        nombreDeDispensario: 'Centro de Salud Mental DR',
        ano: 2024,
        rangoDeEdad: '25-35',
        provincia: 'Santo Domingo',
        padresDivorciados: false,
        observacion: 'Primera consulta',
        fiscalia: null,
        embarazadas: false,
        nssOContrato: '12345678901',
        noAutorizacion: 'AUTH-2024-001',
        valorReclamado: 2500,
        totalDeReclamaciones: 1,
        revisado: true,
        validFact: true,
        objetado: false,
        idCentro: '507f1f77bcf86cd799439012'
    },
    {
        id: '507f1f77bcf86cd799439013',
        fecha: new Date('2024-03-16'),
        mes: 'Marzo',
        especialista: 'Dra. Ana Martinez',
        tipoDeServicio: 'Terapia Familiar',
        nombrePaciente: 'Carlos Sánchez',
        edad: 15,
        nacionalidad: 'Dominicana',
        noCedula: '002-0234567-8',
        genero: 'Masculino',
        solicitante: 'Familiar',
        nombreSolicitante: 'Laura Sánchez',
        direccion: 'Av. Independencia #456, Santo Domingo Norte',
        tipoDePaciente: 'Ambulatorio',
        afiliacionArs: 'ARS Humano',
        categoriaDiagnostico: 'Problemas familiares',
        descripcionDiagnostico: 'Conflictos de comunicación familiar',
        medicamento: 'N/A',
        nombreDeDispensario: 'Centro Familiar DR',
        ano: 2024,
        rangoDeEdad: '13-17',
        provincia: 'Santo Domingo',
        padresDivorciados: true,
        observacion: 'Sesión familiar programada',
        fiscalia: null,
        embarazadas: false,
        nssOContrato: '23456789012',
        noAutorizacion: 'AUTH-2024-002',
        valorReclamado: 3000,
        totalDeReclamaciones: 1,
        revisado: false,
        validFact: true,
        objetado: false,
        idCentro: '507f1f77bcf86cd799439012'
    },
    {
        id: '507f1f77bcf86cd799439014',
        fecha: new Date('2024-03-17'),
        mes: 'Marzo',
        especialista: 'Dr. Roberto Gómez',
        tipoDeServicio: 'Evaluación Psiquiátrica',
        nombrePaciente: 'Ana Morales',
        edad: 32,
        nacionalidad: 'Dominicana',
        noCedula: '003-0345678-9',
        genero: 'Femenino',
        solicitante: 'Referido',
        nombreSolicitante: 'Dr. Luis Mendez',
        direccion: 'Calle Central #789, Ens. Altagracia de Herrera, Santo Domingo Oeste',
        tipoDePaciente: 'Urgencia',
        afiliacionArs: 'ARS Universal',
        categoriaDiagnostico: 'Trastornos del estado de ánimo',
        descripcionDiagnostico: 'Depresión mayor',
        medicamento: 'Fluoxetina 20mg',
        nombreDeDispensario: 'Hospital Psiquiátrico DR',
        ano: 2024,
        rangoDeEdad: '30-40',
        provincia: 'Santo Domingo',
        padresDivorciados: false,
        observacion: 'Requiere seguimiento semanal',
        fiscalia: null,
        embarazadas: true,
        nssOContrato: '34567890123',
        noAutorizacion: 'AUTH-2024-003',
        valorReclamado: 4500,
        totalDeReclamaciones: 1,
        revisado: true,
        validFact: true,
        objetado: true,
        idCentro: '507f1f77bcf86cd799439012'
    }
];

export const defualtFields = {
    fecha: "",
    mes: '',
    especialista: '',
    tipoDeServicio: '',
    nombrePaciente: '',
    edad: 0,
    nacionalidad: '',
    noCedula: '',
    genero: '',
    solicitante: '',
    nombreSolicitante: '',
    direccion: '',
    tipoDePaciente: '',
    afiliacionArs: '',
    categoriaDiagnostico: '',
    descripcionDiagnostico: '',
    medicamento: '',
    nombreDeDispensario: '',
    ano: 0,
    rangoDeEdad: '',
    provincia: '',
    padresDivorciados: false,
    observacion: '',
    fiscalia: null,
    embarazadas: false,
    nssOContrato: '',
    noAutorizacion: '',
    valorReclamado: 0,
    totalDeReclamaciones: 0,
    revisado: false,
    validFact: false,
    objetado: false,
    idCentro: ''
}
